# Generated by Django 4.2.5 on 2024-06-10 11:44

import os
from pathlib import Path

from django.core.management import call_command
from django.db import migrations


def forwards_func(apps, schema_editor):
    try:
        from module.general.models.service import Service

        objects = [
            {
                'pk': 7,
                'attributes': {
                    'enabled': False
                }
            },
            {
                'pk': 10,
                'attributes': {
                    'enabled': False
                }
            }
        ]
        for info in objects:
            try:
                obj = Service.objects.get(id=info['pk'])
                for field, new_value in info['attributes'].items():
                    setattr(obj, field, new_value)
                obj.save()
            except (Service.DoesNotExist, Service.MultipleObjectsReturned):
                pass
    except ImportError:
        pass
    CURRENT_PATH = Path(__file__).parent.resolve()
    data_path = os.path.join(CURRENT_PATH, 'data')
    data_file_names = [
        'service2.json',
    ]
    for filename in data_file_names:
        call_command('loaddata', os.path.join(data_path, filename))


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_loademployees'),
    ]

    operations = [
        migrations.RunPython(code=forwards_func, reverse_code=reverse_func),
    ]
