# Generated by Django 4.2.5 on 2024-06-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_loadanddisableservice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['code', 'reference', 'st_and_num', 'complement', 'reference', 'muni', 'schedules', 'maps_url', 'latitude', 'longitude', 'changed_by', 'created_at', 'updated_at']},
        ),
        migrations.AddField(
            model_name='address',
            name='schedules',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicaladdress',
            name='schedules',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='reference',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicaladdress',
            name='reference',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
