# Generated by Django 5.0.7 on 2024-08-08 16:01

import os
from pathlib import Path

from django.core.management import call_command
from django.db import migrations, models

CURRENT_PATH = Path(__file__).parent.resolve()


def forwards_func(apps, schema_editor):
    CURRENT_PATH = Path(__file__).parent.resolve()
    data_path = os.path.join(CURRENT_PATH, 'data')
    data_file_names = [
        'employee4.json',
    ]
    for filename in data_file_names:
        call_command('loaddata', os.path.join(data_path, filename))


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_loademployees'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['code', 'first_name', 'last_name', 'email_addr', 'enabled', 'changed_by', 'created_at', 'updated_at']},
        ),
        migrations.AddField(
            model_name='employee',
            name='email_addr',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='email_addr',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.RunPython(code=forwards_func, reverse_code=reverse_func),
    ]
