# Generated by Django 5.0.7 on 2024-08-05 10:25

from pathlib import Path

from django.db import migrations

CURRENT_PATH = Path(__file__).parent.resolve()


def forwards_func(apps, schema_editor):
    try:
        from module.general.models.service_account import ServiceAccount

        objects = [
            {
                'pk': 5,
                'attributes': {
                    'enabled': False
                }
            },
        ]
        for info in objects:
            try:
                obj = ServiceAccount.objects.get(id=info['pk'])
                for field, new_value in info['attributes'].items():
                    setattr(obj, field, new_value)
                obj.save()
            except (ServiceAccount.DoesNotExist,
                    ServiceAccount.MultipleObjectsReturned):
                pass
    except ImportError:
        pass


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_historicalserviceservice_serviceservice'),
    ]

    operations = [
        migrations.RunPython(code=forwards_func, reverse_code=reverse_func),
    ]
