# Generated by Django 4.2.5 on 2023-12-20 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['doc_num', 'reference', 'currency', 'web_order_ref', 'sale_channel', 'seller', 'create_date', 'tax_date', 'commit_date', 'updtd_commit_date', 'ship_addr', 'bill_addr', 'customer', 'contact', 'local_total_dcnt', 'doc_total_dcnt', 'local_total_tax', 'doc_total_tax', 'local_total_amt', 'doc_total_amt', 'status', 'enabled', 'obs', 'changed_by', 'created_at', 'updated_at'], 'permissions': [('edit_all_order_delivery_form', 'Can edit all order delivery form fields'), ('edit_commit_date', 'Can edit the order commitment date field'), ('edit_all_order_delivery_form_from_api', 'Can edit the order commitment date field from API')]},
        ),
    ]
