# Generated by Django 4.2.5 on 2023-10-31 15:43

import os
from pathlib import Path

from django.core.management import call_command
from django.db import migrations

CURRENT_PATH = Path(__file__).parent.resolve()


def forwards_func(apps, schema_editor):
    CURRENT_PATH = Path(__file__).parent.resolve()
    data_path = os.path.join(CURRENT_PATH, 'data')
    data_file_names = [
        'sale_channel.json',
        'sale_channel_service.json',
        'status.json',
        'status_service.json',
    ]
    for filename in data_file_names:
        call_command('loaddata', os.path.join(data_path, filename))


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    CURRENT_PATH = Path(__file__).parent.resolve()
    current_filename = os.path.basename(__file__)
    filenames = []

    for filename in os.listdir(CURRENT_PATH):
        if filename != current_filename:
            if not filename[0].isalnum():
                continue
            if os.path.isfile(os.path.join(CURRENT_PATH, filename)):
                filenames.append(filename)
    filenames.sort()

    dependencies = [('order', filename) for filename in filenames]

    operations = [
        migrations.RunPython(code=forwards_func, reverse_code=reverse_func),
    ]
