# Generated by Django 4.2.5 on 2023-09-27 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdelivery',
            options={},
        ),
    ]
