# Generated by Django 4.2.5 on 2023-09-27 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('delivery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='order_delivery',
            field=models.ManyToManyField(through='order.OrderDelivery', to='order.grouping'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='service_acct',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='general.serviceaccount'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.status'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='service_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.statusservice'),
        ),
        migrations.AddField(
            model_name='branch',
            name='addr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.address'),
        ),
        migrations.AddField(
            model_name='branch',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branch',
            name='service_acct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.serviceaccount'),
        ),
    ]
