# Generated by Django 4.2.5 on 2024-08-05 11:40

import os
from pathlib import Path

from django.conf import settings
from django.core.management import call_command
from django.db import migrations


CURRENT_PATH = Path(__file__).parent.resolve()


def forwards_func(apps, schema_editor):
    CURRENT_PATH = Path(__file__).parent.resolve()
    data_path = os.path.join(CURRENT_PATH, 'data')
    data_file_names = [
        'pay_type_service2.json',
        'type_service2.json',
    ]
    for filename in data_file_names:
        call_command('loaddata', os.path.join(data_path, filename))


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery', '0004_loadnewservice'),
    ]

    operations = [
        migrations.RunPython(code=forwards_func, reverse_code=reverse_func),
    ]
