# Generated by Django 4.2.5 on 2024-08-05 11:40

from pathlib import Path

from django.conf import settings
from django.db import migrations

CURRENT_PATH = Path(__file__).parent.resolve()


def forwards_func(apps, schema_editor):
    try:
        from module.delivery.models.branch import Branch

        objects = [
            {
                'pk': 2,
                'attributes': {
                    'enabled': False
                }
            },
            {
                'pk': 3,
                'attributes': {
                    'enabled': False
                }
            }
        ]
        for info in objects:
            try:
                obj = Branch.objects.get(id=info['pk'])
                for field, new_value in info['attributes'].items():
                    setattr(obj, field, new_value)
                obj.save()
            except (Branch.DoesNotExist, Branch.MultipleObjectsReturned):
                pass
    except ImportError:
        pass


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery', '0005_loadnewservicedata'),
    ]

    operations = [
        migrations.RunPython(code=forwards_func, reverse_code=reverse_func),
    ]
