# Generated by Django 4.2.5 on 2023-09-22 14:19

import os
import pathlib

from django.conf import settings
from django.core.management import call_command
from django.db import migrations, models

from classes.starken.agency import Agency


def forwards_func(apps, schema_editor):
    current_path = pathlib.Path(__file__).parent.resolve()
    data_path = os.path.join(current_path, 'data')
    data_file_names = [
        'carrier.json',
        'doc_type.json',
        'pay_type.json',
        'service.json',
        'type.json',
        'status.json',
    ]
    for filename in data_file_names:
        call_command('loaddata', os.path.join(data_path, filename))
    Agency().app_sync()
    data_file_names = [
        'option.json',
    ]
    for filename in data_file_names:
        call_command('loaddata', os.path.join(data_path, filename))


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='order_delivery',
            field=models.ManyToManyField(through='order.OrderDelivery', to='order.grouping'),
        ),
        migrations.RunPython(code=forwards_func, reverse_code=reverse_func),
    ]
