# Generated by Django 4.2.5 on 2023-09-13 10:52

import os
import pathlib

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.core.management import call_command
from django.db import migrations, models

from classes.starken.agency import Agency


def forwards_func(apps, schema_editor):
    current_path = pathlib.Path(__file__).parent.resolve()
    data_path = os.path.join(current_path, 'data')
    data_file_names = [
        'carrier.json',
        'doc_type.json',
        'pay_type.json',
        'service.json',
        'type.json',
    ]
    for filename in data_file_names:
        call_command('loaddata', os.path.join(data_path, filename))
    Agency().app_sync()
    data_file_names = [
        'option.json',
    ]
    for filename in data_file_names:
        call_command('loaddata', os.path.join(data_path, filename))


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaldelivery',
            name='order_grouping',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='order.grouping'),
        ),
        migrations.AddField(
            model_name='historicalcarrier',
            name='changed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcarrier',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalagency',
            name='addr',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='general.address'),
        ),
        migrations.AddField(
            model_name='historicalagency',
            name='carrier',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='delivery.carrier'),
        ),
        migrations.AddField(
            model_name='historicalagency',
            name='changed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalagency',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.delivery'),
        ),
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.documenttype'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='delivery',
            name='order_grouping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.grouping'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agency',
            name='addr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.address'),
        ),
        migrations.AddField(
            model_name='agency',
            name='carrier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery.carrier'),
        ),
        migrations.AddField(
            model_name='agency',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(code=forwards_func, reverse_code=reverse_func)
    ]
