name: Pull request event

on: 
  pull_request:
    ypes: [opened, reopened]

run-name: ${{ github.actor }} trigger pipeline
jobs:
  trigger-run:
    name: Dispatch on pull request
    runs-on: ubuntu-latest
    steps:
      - name: Install the gh cli
        uses: actions/checkout@v2
        env:
          GH_HOST: gitlab.com
          GH_REPO: gitlab.com/genosur-cl/despachos
        with:
          version: 2.12.1
      - run: |
          gh version
          echo ${{ secrets.PIPELINE_USER_TOKEN }} > token.txt
          gh auth login --with-token < token.txt
          echo $GITHUB_HEAD_REF
          echo '{"branch_name":"'$GITHUB_HEAD_REF'"}' | gh workflow run on-pull-request.yml --ref pipeline --json
      
          
          